### ISSUE TITLE
Error copying Carousel plugin

### ISSUE THREAD

**Issue by davidetruffo** [jrief/djangocms-cascade#160] opened 2016-04-21 16:08 UTC
Hi!
I bumped into an error while copying a carousel plugin (bootstrap).
I'm having an hard time debugging it as i haven't understood if the problem is related to the plugin, or to django itself (or both).

What i do:
add a Container plugin, then a Row, then a Column, then a Carousel.
Then i try to copy (not copy&paste) the Carousel (or the column).
I get this: 
````
KeyError at /admin/cms/page/copy-plugins/ 'breakpoints' Request Method: POST Request URL: http://192.168.0.2:8000/admin/cms/page/copy-plugins/ Django Version: 1.8.4 Python Executable: /Users/davidetruffo/Projects/venvs/tt/bin/python Python Version: 3.4.3 Python Path: ['/Users/davidetruffo/Projects/tt', '/Users/davidetruffo/Projects/venvs/tt/lib/python34.zip', '/Users/davidetruffo/Projects/venvs/tt/lib/python3.4', '/Users/davidetruffo/Projects/venvs/tt/lib/python3.4/plat-darwin', '/Users/davidetruffo/Projects/venvs/tt/lib/python3.4/lib-dynload', '/Users/davidetruffo/.pyenv/versions/3.4.
````
in the small black overlay from the cms, then the page reloads.

Could anyone double check if it happens to you too?
A couple of versions:
Django==1.8.4
django-cms==3.1.4
djangocms-cascade==0.7.3
(i can't use cascade 0.8.1 'cause i can't upgrade to the latest cms right now, sadly)

Thanks!

**Comment by jrief** [comment] 2016-04-21 16:39
could you please check for changes in boostrap3/container.py between 0.7.3 and 0.8.1. I remember that something changed in between. If so, please try to apply that patch onto 0.7.3. We then could create a feature branch and release 0.7.4.

**Comment by davidetruffo** [comment] 2016-04-22 08:27
HI again @jrief,
I applied the changes from 0.8.1 to 0.7.3 in bootstrap3/container.py as suggested, but i'm still getting the same error.

I've also tried to install v0.8.2 (with a small workaround to skip the revision thing and make it work with cms v3.1.4) and the copy error still persists. 

Any idea?

**Comment by davidetruffo** [comment] 2016-04-22 09:11
to narrow it down a bit,
the error happens in [bootstrap3/carousel.py:115](https://github.com/jrief/djangocms-cascade/blob/0.7.3/cmsplugin_cascade/bootstrap3/carousel.py#L115)

complete_glossary has no "breakpoints" key. 
What's the logic behind the `sanitize_model`?

````
def sanitize_model(cls, obj):
        sanitized = super(CarouselPlugin, cls).sanitize_model(obj)
        complete_glossary = obj.get_complete_glossary()
        # fill all invalid heights for this container to a meaningful value
        max_height = max(obj.glossary['container_max_heights'].values())
        pattern = re.compile(r'^(\d+)px$')
        for bp in complete_glossary['breakpoints']:  <<<<< ERROR HAPPENS HERE!
            if not pattern.match(obj.glossary['container_max_heights'].get(bp, '')):
                obj.glossary['container_max_heights'][bp] = max_height
        return sanitized
`````

**Comment by jrief** [comment] 2016-04-24 19:42
Bug confirmed, but only if you did not publish the page yet.

This has to to with the way django-CMS handles public and draft pages. The DOM tree of plugins for draft pages may not be available then.

Currently I haven't found any quick solution for this. One workaround is to first publish the page before creating a copy. Otherwise the plugin tree is not ready.

Please retry and confirm or disapprove this assumption.

**Comment by davidetruffo** [comment] 2016-04-25 08:12
Hi, I just tried again after publishing the page, and the error persists. :(

**Comment by jrief** [comment] 2016-04-25 08:43
Please retry with the latest version from github.

**Comment by davidetruffo** [comment] 2016-04-25 09:15
I can't test the very last version because of the revision thing (and i can't upgrade the cms right now), BUT i can confirm that this tiny commit you did fixes the problem :)

**Comment by davidetruffo** [comment] 2016-05-13 11:55
@jrief do you have any news about this (if it is planned to be released anytime soon as 0.7.4)?

**Comment by davidetruffo** [comment] 2016-05-13 15:45
@jrief 
My client complained for a bug (maybe related, but i don't think so), and while debugging, i found that a similar line could break as well and specifically [this one](https://github.com/jrief/djangocms-cascade/blob/master/cmsplugin_cascade/bootstrap3/utils.py#L136) in `bootstrap3/utils.py`

Applying the same workaround would break [later on](https://github.com/jrief/djangocms-cascade/blob/master/cmsplugin_cascade/bootstrap3/utils.py#L179), because the variable `image_height` would not exist.

I'm not sure if this would break anything, it's just an heads up since i found a similar loop through breakpoints. :)

Thanks

**Comment by frnhr** [comment] 2016-05-13 16:00
I'm running into an issue with images that might be related.

Whenever I copy an Image plugin, it doesn't render the image. Edit
popup form shows fine, and keeps the data between saves, but image is not
rendered.

Here is what's even more strange. Please bear with me for a few sentences,
I'm sure this can be explained in a more conscience way...
I have BoostrapColum with one Image plugin in. If I copy the column plugin
and paste it, the pasted Image plugin has the same problem as above. BUT,
here is what's very interesting - if I delete the pasted Image plugin and
create a new Image plugin in the same place, that new Image plugin will
also have the same problem! That is, a new Image plugin in a pasted column
plugin won't render its image.

I hope it gives @jrief some clues.


On Friday, 13 May 2016, Davide Truffo <notifications@github.com> wrote:

> @jrief <https://github.com/jrief>
> My client complained for a bug (maybe related, but i don't think so), and
> while debugging, i found that a similar line could break as well and
> specifically this one
> <https://github.com/jrief/djangocms-cascade/blob/master/cmsplugin_cascade/bootstrap3/utils.py#L136>
> in bootstrap3/utils.py
>
> Applying the same workaround would break later on
> <https://github.com/jrief/djangocms-cascade/blob/master/cmsplugin_cascade/bootstrap3/utils.py#L179>,
> because the variable image_height would not exist.
>
> I'm not sure if this would break anything, it's just an heads up since i
> found a similar loop through breakpoints. :)
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jrief/djangocms-cascade/issues/160#issuecomment-219081893>
>


-- 
LP,
Fran

**Comment by jrief** [comment] 2016-05-14 06:44
Ok, thanks for reporting. I will probably have time end of next week to look at it. If you find any additional hints please report them here

**Comment by jrief** [comment] 2016-05-14 06:49
Please check out the branch 'sections' and test against it. I changed some copying functionality there.

**Comment by jrief** [comment] 2016-05-15 16:49
@frnhr I just tried out to reproduce the above using your explanation. In my setup everything works fine, with one exception, when I tried to copy the image for the first time. This seems to be a bug in the CMS itself. It might be fixed using this PR: https://github.com/divio/django-cms/pull/5296

**Comment by jrief** [comment] 2016-06-13 14:21
@davidetruffo Today I made many changes in Cascade. They are published in branch "sections", which will become version 0.9.0. It allows to set links onto section bookmarks (ie. id="...") anywhere in the page.

These adoptions where required because of some API changes in CMS version 3.3.0. It might be that they also fix the problems you described.

**Comment by davidetruffo** [comment] 2016-06-20 09:49
Hi @jrief 
Thanks for the heads up, i'm drowning in a different project right now, so i won't have much time to test it carefully. Will do asap

**Comment by jrief** [comment] 2016-06-20 10:02
Upcoming version 0.9 will support DjangoCMS-3.3 and there a lot changed regarding plugin configuration, etc.

**Comment by jrief** [comment] 2016-10-04 20:17
I just retested to copy a carousel with 2 slides, and pasted it onto another page.
This is with Cascade version 0.10 and cms-3.3.2
Everything works fine, so I close this issue.

**Closed by jrief** 2016-10-04 20:17 UTC
