### ISSUE TITLE
"Icon in text" not rendering?

### ISSUE THREAD

**Issue by racitup** [jrief/djangocms-cascade#252] opened 2017-09-08 17:19 UTC
I'm trying to use the iconfont plugin inside a text box but it doesn't seem to be rendering.
I have loaded fontawesome, and the icon appears in the text editor when added but renders to below in the real page (notice the <i> tags are inside the string quotes), and when editing the text box again, the icon is gone. Any ideas?

`<cms-plugin title="Icon in text - fontawesome: <i class=&quot;icon-mail&quot;></i>" id="1685" alt="Icon in text - fontawesome: <i class=&quot;icon-mail&quot;></i> "></cms-plugin>`

**Comment by jrief** [comment] 2017-09-08 20:20
I never experienced this, but it seems as if someone text is not marked as safe.
Could you please send me the exact placeholder structure as JSON data (through **Persisted Placeholder Content**).

**Comment by jrief** [comment] 2017-09-13 06:53
Did you use this in your settings.py:

```
CKEDITOR_SETTINGS = {
    'language': '{{ language }}',
    'skin': 'moono',
    'toolbar': 'CMS',
    'toolbar_HTMLField': [
        ['Undo', 'Redo'],
        ['cmsplugins', '-', 'ShowBlocks'],
        ['Format', 'Styles'],
        ['TextColor', 'BGColor', '-', 'PasteText', 'PasteFromWord'],
        ['Maximize', ''],
        '/',
        ['Bold', 'Italic', 'Underline', '-', 'Subscript', 'Superscript', '-', 'RemoveFormat'],
        ['JustifyLeft', 'JustifyCenter', 'JustifyRight'],
        ['HorizontalRule'],
        ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Table'],
        ['Source']
    ],
    'stylesSet': format_lazy('default:{}', reverse_lazy('admin:cascade_texticon_wysiwig_config')),
}
```

**Comment by racitup** [comment] 2017-09-13 09:30
Yes, it's exactly the same

**Comment by jrief** [comment] 2017-09-13 10:15
I just was able to reproduce it. It seems to be a regression.

**Comment by jrief** [comment] 2017-09-13 10:23
well it works in my local dev-env, but it doesn't in my Docker image. That's weird, since they both use the same dependencies. I'll investigate this further.

**Comment by jrief** [comment] 2017-09-16 09:21
well, in my Docker image I'm using Python 3.5.3 whereas for local dev, I use Python 2.7.12.
Probably it's just a stupid unicode problem.

**Comment by racitup** [comment] 2017-09-16 11:52
That would tie in, I'm using 3.5.2. I'll try with 2.7 and let you know..

**Comment by racitup** [comment] 2017-09-16 12:25
I get the same result with 2.7.12..

**Comment by racitup** [comment] 2017-09-17 15:00
My environment for python 2.7 for comparison:
$ pip freeze
beautifulsoup4==4.6.0
bs4==0.0.1
cmsplugin-css-background==0.1.1.dev31+g89b674b
defusedxml==0.5.0
dj-database-url==0.4.2
dj-static==0.0.6
Django==1.10.7
django-admin-sortable2==0.6.11
django-allauth==0.23.0
django-angular==1.1.2
django-appconf==1.0.2
django-classy-tags==0.8.0
django-cms==3.4.4
django-compressor==2.1.1
django-currencies==0.4.0
django-debug-toolbar==1.6
django-filer==1.2.8
django-filter==1.0.4
django-formtools==2.0
django-fsm==2.6.0
django-fsm-admin==1.2.4
django-haystack==2.5.1
django-ipware==1.1.6
django-mptt==0.8.7
django-parler==1.7
django-polymorphic==1.0.2
django-post-office==3.0.3
django-redis-cache==1.6.0
django-redis-sessions==0.5.0
django-rest-auth==0.9.1
django-sass-processor==0.5.4
django-sekizai==0.10.0
Django-Select2==5.11.1
django-shop==0.11
django-treebeard==4.1.2
djangocms-admin-style==1.2.7
djangocms-bootstrap3==0.3.1
djangocms-cascade==0.14.1
djangocms-text-ckeditor==3.5.0
djangorestframework==3.6.3
djangoshop-currencies==0.2.0.dev0
djangoshop-stripe==0.2.3
djangoshop-subscribe==0.2.0.dev0
drf-haystack==1.6.1
easy-thumbnails==2.3
elasticsearch==1.7.0
enum34==1.1.6
gunicorn==19.6.0
hiredis==0.2.0
html5lib==0.9999999
jsonfield==2.0.2
libsass==0.12.3
oauthlib==1.0.3
olefile==0.44
Pillow==4.2.1
pluggy==0.3.1
py==1.4.30
pycrypto==2.6.1
Pygments==2.0.2
python-dateutil==2.5.3
python-openid==2.2.5
python3-openid==3.0.10
pytz==2017.2
rcssmin==1.0.6
redis==2.10.3
requests==2.14.2
requests-oauthlib==0.5.0
rjsmin==1.0.12
six==1.10.0
sqlparse==0.2.3
static3==0.7.0
stripe==1.37.0
Unidecode==0.4.21
urllib3==1.12

**Comment by haricot** [comment] 2018-03-31 11:19
pip install djangocms-text-ckeditor==3.5.3
./manage collectstatic
This should solve the problem.

**Closed** 2018-04-16 15:43 UTC
Labels: bug
